authors:
  revelwood:
    name: Revelwood
    description: Revelwood Team
    avatar: https://avatars.githubusercontent.com/u/158498073
    url: https://github.com/Revelwood
  alex:
    name: Alex
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/25189808
    url: https://github.com/alexlichtenberger
  ivan:
    name: Ivan
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/140555985
    url: https://github.com/icepero
  marc:
    name: Marc
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/157613232
    url: https://github.com/massenza-001
  rob:
    name: Rob
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/2768460
    url: https://github.com/rgordy
  zach:
    name: Zach
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/157613241
    url: https://github.com/rw-zach
