name: Publish to Python Package Index
on:
  release:
    types: [published]
jobs:
  pypi:
    runs-on: [ubuntu-latest]
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --locked
      - run: uv build
      - run: uv publish ./dist/*
